#!/usr/bin/env ansible-playbook
---

- name: Creates {{ title }}
  hosts: localhost
  gather_facts: False

  vars:
    title: ansible-cfg dirs
    dir: '{{ ansible_facts.env.PWD }}'

  tasks:

    - include_vars: '{{ dir }}/ansible-cfg/dirs.yml'

    - file: { path: '{{ dir}}/{{ item }}', state: directory }
      loop: '{{ dirs }}'
      name: Creates {{ title }}

    - copy: { dest: &gitignore '{{ dir }}/.gitignore', content: '*~', force: False }

    - lineinfile: { path: *gitignore, line: '{{ item }}' }
      vars: { more: [ ansible-cfg, ansible.cfg, ext, vault-pass.py, private-repos.yml, keys.yml ] }
      loop: '{{ gitignore + more }}'
      name: Do not commit {{ title }}
