#!/usr/bin/env ansible-playbook
---

- name: Creates {{ title }}
  hosts: localhost
  gather_facts: True

  vars:
    title: ansible-cfg dirs
    dir: '{{ ansible_facts.env.PWD }}'
    confdir: ansible_cfg
    exclude: '{{ dir }}/.git/info/exclude'

  tasks:

    - include_vars: '{{ dir }}/{{ confdir }}/dirs.yml'

    - file: { path: '{{ dir}}/{{ item }}', state: directory }
      loop: '{{ dirs }}'
      name: Creates {{ title }}

    - copy: { dest: &gitignore '{{ dir }}/.gitignore', content: '*~', force: False }

    - lineinfile: { path: '{{ exclude }}', line: '{{ item }}' }
      vars: { more: [ '{{ confdir }}', ansible.cfg, ext, vault-pass.py, private-repos.yml, keys.yml, inventory ] }
      loop: '{{ gitignore + more }}'
      name: Do not commit {{ title }}
